### ISSUE TITLE
Add markers to map

### ISSUE THREAD

**Issue by skezh** [Rescor/aww#2]
- After you have a map, make a few markers with coordinates you want to add and show them on map.
- Example: https://developers.google.com/maps/documentation/javascript/examples/marker-simple
- Add labels to the markers: https://developers.google.com/maps/documentation/javascript/examples/marker-labels
- Add info windows to the markers when user clicks on them: https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

**Comment by Rescor** [comment]
https://github.com/Rescor/aww/commit/8f0a55abd3270fc8fe1b9443a891a054b59615ad
